# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-03 04:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0008_auto_20171103_0416'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pizza',
            name='toppings',
            field=models.ManyToManyField(related_name='related', related_query_name='related_query', to='polls.Topping'),
        ),
    ]
