# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-03 07:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0010_auto_20171103_0627'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=400)),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destinations', to='polls.Person')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sources', to='polls.Person')),
            ],
        ),
        migrations.AddField(
            model_name='person',
            name='messages',
            field=models.ManyToManyField(through='polls.Message', to='polls.Person'),
        ),
    ]
